name: Firmware CI Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Install ARM GCC
      uses: carlosperate/arm-none-eabi-gcc-action@v1
    - name: Run make
      run: make
      working-directory: ./fw
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dvmv24-fw
        path: |
          ./fw/build/*.bin
          ./fw/build/*.elf
